apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: core-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "core-staging-ingress-ip"
spec:
  rules:
  - host: api.staging.knowlearning.systems
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: core-deno
            port:
              number: 4443