apiVersion: skaffold/v4beta2
kind: Config

build:
  artifacts:
  - image: gcs
    context: ./core/infrastructure/development/
    docker:
      dockerfile: ./gcs.Dockerfile
  - image: redis
    context: ./core/infrastructure/development/
    docker:
      dockerfile: ./redis.Dockerfile
  - image: postgres
    context: ./core/infrastructure/development/
    docker:
      dockerfile: ./postgres.Dockerfile
  - image: core-deno
    context: ./core/
    docker:
      dockerfile: ./core/deno.Dockerfile
profiles:
- name: development
  manifests:
    kustomize:
      paths:
      - ./core/infrastructure/development
  deploy:
    kubeContext: kind-kl-core
    kubectl: {}
- name: staging
  manifests:
    kustomize:
      paths:
      - ./core/infrastructure/staging
  deploy:
    kubectl: {}
- name: production
  manifests:
    kustomize:
      paths:
      - ./core/infrastructure/production
  deploy:
    kubectl: {}
