authorize:
  sameDomain:
    postgres: same_domain_authorization
  crossDomain:
    postgres: cross_domain_authorization
postgres:
  tables: {}
  functions:
    same_domain_authorization:
      returns: BOOLEAN
      language: PLpgSQL
      body: |
        BEGIN
          RETURN TRUE;
        END;
      arguments:
      - name: requestingUser
        type: TEXT
      - name: requestedScope
        type: TEXT
    cross_domain_authorization:
      returns: BOOLEAN
      language: PLpgSQL
      body: |
        BEGIN
          RETURN TRUE;
        END;
      arguments:
      - name: requestingDomain
        type: TEXT
      - name: requestingUser
        type: TEXT
      - name: requestedScope
        type: TEXT
agent: |
  import Agent, { getAgent } from 'npm:@knowlearning/agents/deno.js'

  // XAPI Agent
  const xApiAgent = getAgent('xapi.knowlearning.systems')

  Agent.on('child', child => {
      const { environment: { user } } = child
      child.on('mutate', ({ id, scope, patch, context }) => {
          patch.forEach(async ({ path, value }) => {
            if (path[0] === 'xapi' && path.length === 1 && value) {
              const x = await xApiAgent.state(`xapi/${Agent.uuid()}`)
              Object.assign(x, {
                  ...value,
                  source: id,
                  context
              })
            }
          })
      })
  })

  // TAGS Agent
  const TagAgent = getAgent('tags.knowlearning.systems')
  const agentTags = await TagAgent.state('tags')

  function addTag(tagId, contentId) {
    if (!agentTags.value[tagId]) agentTags.value[tagId] = {}
    agentTags.value[tagId][contentId] = true
  }

  Agent.on('child', child => {
    const { environment: { user } } = child

    child.on('mutate', ({ scope, patch }) => {
      if (scope === 'tags') {
        patch.forEach(async ({ path, value:patchValue }) => {
          if (path.length === 2) {
            const [ tagId, contentId ] = path
            const { value, partition=user } = patchValue
            if (!agentTags[tagId]) agentTags[tagId] = {}
            agentTags[tagId][contentId] = { contributor: user, partition, value }
          }
        })
      }
    })
  })
