apiVersion: v1
kind: ServiceAccount
metadata:
  name: patch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patch
  labels:
    app: patch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patch
  template:
    metadata:
      labels:
        app: patch
    spec:
      serviceAccountName: patch
      terminationGracePeriodSeconds: 10
      containers:
      - name: patch
        image: patch
        resources:
          requests:
            memory: 2048Mi
            cpu: 1000m
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: agent-env
