apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: core-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: core-ingress-ip
    networking.gke.io/managed-certificates: core-ingress-managed-cert
spec:
  rules:
  - host: api.knowlearning.systems
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: core-deno
            port:
              number: 8080
---
# TODO: separate deployment procedure for managed certs and document
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: core-ingress-managed-cert
spec:
  domains:
    - api.knowlearning.systems