apiVersion: v1
kind: Service
metadata:
  name: core-deno
spec:
  type: NodePort
  selector:
    app: core-deno
  ports:
  - name: root-internal
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: root
    protocol: TCP
    port: 4443
    nodePort: 30001
  - name: root-insecure
    protocol: TCP
    port: 32002
    nodePort: 30002
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nats-ui
spec:
  type: NodePort
  selector:
    app: core-deno
  ports:
  - name: nats-ui
    protocol: TCP
    port: 32004
    nodePort: 30004
    targetPort: 8222
