apiVersion: v1
kind: Service
metadata:
  name: core
spec:
  type: NodePort
  selector:
    app: core
  ports:
  - name: root-internal
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: root
    protocol: TCP
    port: 4443
    nodePort: 30001
  - name: root-insecure
    protocol: TCP
    port: 32002
    nodePort: 30002
    targetPort: 8080
