import { uuid, uuidv5, environment, decryptBase64String, decodeBase64, box } from '../utils.js'
import JWTVerification from './verify-jwt.js'
import decryptJSON from './decrypt-json.js'
import Agent from '../agent.js'

const {
  AUTH_SERVICE_SECRET_KEY,
  OAUTH_CREDENTIALS,
  SECRET_ENCRYPTION_KEY
} = environment

const BASE64_PUBLIC_KEY_NAMESPACE = '1b4555f2-a89c-4633-834a-a064c195ab22'
const OAuthProviderCredentials = JSON.parse(OAUTH_CREDENTIALS)

export default function authenticateToken(domain, token, authority) {
  return new Promise( async (resolve, reject) => {
    if (authority === 'core') JWTVerification('core', token, resolve, reject)
    else if (!token || token.length < 32) resolve(anonymousProviderResponse(uuid())) //  the less than 32 is an indicator of token passed on logout TODO: make this exchange more explicit between client and server
    else {
      try {
        const { domain: tokenDomain, provider, code } = JSON.parse(await decryptBase64String(AUTH_SERVICE_SECRET_KEY, token))

        if (tokenDomain !== domain) reject(`INVALID TOKEN DOMAIN: ${domain} != ${tokenDomain}`)
        else if (provider === 'code') {
          //  TODO: assess if this is dead code
          //  TODO: authenticating user's provider should be the user id of the owner
          //  TODO: use code and providing user's config to get user id
          //  TODO: get user name from providing user (encrypted and decrypted w/ users's code)
          const id = uuid()
          resolve({
            user: id,
            provider_id: id,
            provider: 'providing user\'s id',
            info: { name: 'from providing user', picture: null }
          })
        }
        else if (OAuthProviderCredentials[provider.toUpperCase()]) {
          JWTVerification(provider, code, resolve, reject)
        }
        else {
          const { userPublicKey, userEncryptedInfo } = JSON.parse(
            await decryptBase64String(AUTH_SERVICE_SECRET_KEY, code)
          )

          const credentialId = uuidv5(userPublicKey, BASE64_PUBLIC_KEY_NAMESPACE)

          const { user, providerPublicKey } = await Agent.state(credentialId)
          const { owner: credentialOwner  } = await Agent.metadata(credentialId)
          const { owner: userOwner        } = await Agent.metadata(user)

          // Prove authenticating user has owner provided user secret
          const {
            created,
            providerEncryptedInfo
          } = decryptJSON(SECRET_ENCRYPTION_KEY, userPublicKey, userEncryptedInfo)

          // Prove user info was generated by owner
          const {
            user: providerDeclaredUser,
            info
          } = decryptJSON(SECRET_ENCRYPTION_KEY, providerPublicKey, providerEncryptedInfo)

          if ( credentialOwner === userOwner
            && providerDeclaredUser === user
            && Date.now() - created < 30_000
          ) {
            resolve({ user, provider_id: user, provider: userOwner, info})
          }
          else {
            reject('ERROR VERIFYING CODE')
          }
        }
      }
      catch (error) {
        console.warn(`ERROR DECRYPTING OR PARSING TOKEN FOR ${domain}`, error)
        reject('ERROR DECRYPTING OR PARSING TOKEN')
      }
    }
  })
}

function anonymousProviderResponse(id) {
  return {
    user: id,
    provider_id: id,
    provider: 'anonymous',
    info: { name: 'anonymous', picture: null }
  }
}
