site_name: Know Learning Documentation
repo_url: https://github.com/knowlearning/documentation
edit_uri: edit/trunk/docs/
nav:
  - Home: index.md
  - Introduction:
    - Installation: introduction/installation.md
    - Authentication: introduction/authentication.md
    - States: introduction/states.md
    - Files: introduction/files.md
    - Historical Data: introduction/historical-data.md
    - Relational Data: introduction/relational-data.md
    - Authorization: introduction/authorization.md
  - Reference:
    - Initialization: reference/initialization.md
    - Agents: reference/agents.md
    - Relational Data: reference/relational-data.md
    - Authorization: reference/authorization.md
  - How-Tos: how-tos/index.md
  - Tutorials:
    - Recommended App Scaffold: tutorials/recommended-app-scaffold.md
  - Frameworks:
    - Vue: frameworks/vue.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: material
  logo: assets/logo-white.svg
  favicon: assets/logo-orange.svg
  features:
    - content.action.edit
  palette:
    primary: orange
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
extra:
  generator: false
extra_css:
- stylesheets/index.css