services:
  gcs-emulator:
    image: fsouza/fake-gcs-server:1.49.3
    container_name: gcs-emulator
    ports:
      - 4443:4443
      - 8000:8000
    volumes:
      - ./local-gcs-bucket:/data/local-gcs-bucket
    command: >
      -scheme both
      -port 4443
      -port-http 8000
      -log-level debug
      -cors-headers x-upload-content-type,x-goog-content-sha256,x-goog-resumable,x-goog-meta-user,x-goog-meta-type,x-goog-meta-name,x-goog-meta-edit,x-goog-meta-view,x-goog-meta-base,x-goog-meta-domain
      -external-url https://localhost:4443
      -public-host localhost

  postgres:
    image: postgres:alpine3.18
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=insecure-development-password

  authorizer:
    build: ../source/authorization
    ports:
      - 8765:8765
    container_name: authorizer
    env_file:
      - ./.credentials/development
      - ./environment/development
    volumes:
      - ../../packages/agent:/agent
    depends_on:
      - postgres
      - gcs-emulator
      - nats
      - redis

  nats:
    image: nats:2.10.18
    container_name: nats
    ports:
      - 4222:4222
      - 8222:8222
      - 8080:8080
    volumes:
      - ../source/nats.conf:/etc/nats/nats.conf
    command: -c /etc/nats/nats.conf

  redis:
    image: redis/redis-stack:7.4.0-v0
    container_name: redis
    ports:
      - 6379:6379
    env_file:
      - ./.credentials/development
      - ./environment/development
